### ISSUE TITLE
OkHttpClientHttpRequestFactory prevents usings OkHttp interceptors

### ISSUE THREAD

**Issue by clemp6r** [spring-projects/spring-android#24]
OkHttpClientHttpRequestFactory uses OkUrlFactory.

With OkHttp 2.2.0 comes a new great feature: Interceptors. Interceptors  won't work when using OkUrlFactory, as explained here: https://github.com/square/okhttp/wiki/Interceptors

Can you provide a different implementation of OkHttpClientHttpRequestFactory that don't use OkUrlFactory so we can use interceptors?

(FYI http://facebook.github.io/stetho/ needs OkHttp interceptors)

**Comment by gmarques33** [comment]
I'm also trying to use Stetho with interceptors and I have this problem too.
I'm trying to use StethoURLConnectionManager with a custom ClientHttpRequestFactory, but I can get only request on chrome dev tools.

**Comment by WonderCsabo** [comment]
Guys, how an other implementation should look like? I assume it could not be achieved easily.

**Comment by royclarkson** [comment]
Spring Framework recently included OkHttp support. It can probably be adapted for android.

**Comment by WonderCsabo** [comment]
Can you reference the changeset which did that?

**Comment by WonderCsabo** [comment]
@royclarkson can you point me to the changeset? :)

**Comment by WonderCsabo** [comment]
Never mind. :wink: Thanks for fixing this!

**Comment by royclarkson** [comment]
@WonderCsabo I spent some time last night and modified the implementation from Spring Framework. It should be in a good place now.

**Comment by royclarkson** [comment]
I pushed 2.0.0.M3 with the latest OkHttp support. It's available for testing from the [spring repository](https://repo.spring.io/libs-milestone/).

**Comment by WonderCsabo** [comment]
@royclarkson i am getting this exception:

```
java.lang.IllegalArgumentException: method POST must have a request body.
	at com.squareup.okhttp.Request$Builder.method(Request.java:244)
	at org.springframework.http.client.OkHttpClientHttpRequest.executeInternal(OkHttpClientHttpRequest.java:85)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:84)
	at org.springframework.http.client.InterceptingClientHttpRequest$RequestExecution.execute(InterceptingClientHttpRequest.java:91)
	at my.super.secret.package.AuthorizationInterceptor.intercept(AuthorizationInterceptor.java:29)
	at org.springframework.http.client.InterceptingClientHttpRequest$RequestExecution.execute(InterceptingClientHttpRequest.java:81)
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:67)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:84)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:536)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:499)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:447)
```
The same call worked with M2.

**Comment by royclarkson** [comment]
Hmm. Looks like there was a change in OkHttp 2.4 to require a request body. The dependency was updated from 2.1.0 to 2.4.0 in the M3 release. Would you mind opening a new issue please? We can probably handle this situation.

**Comment by WonderCsabo** [comment]
@royclarkson i am not sure about that. I was already using OkHttp 2.4 and i experienced no problems with the old `OkHttpRequestFactory` implementation in M2.

**Comment by royclarkson** [comment]
M2 was using the [UrlConnection API](https://github.com/spring-projects/spring-android/blob/de3e8e4ff09ea8a11d400eb2ed6311effc315720/spring-android-rest-template/src/main/java/org/springframework/http/client/OkHttpClientHttpRequestFactory.java), instead of a proper implementation. That might be why it was still working. I'm guessing at this point.

**Comment by WonderCsabo** [comment]
Yeah, i know that. :) I opened #25.

**Comment by royclarkson** [comment]
Heh. Thanks for the reminder. :)
